[package]
name = "rustineers"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "crates/ridge_regression_1d",
]

[dependencies]
ridge_regression_1d = { path = "crates/ridge_regression_1d" }
