name: Rust lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Check formatting and clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions/setup-rust@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install just
        run: |
          cargo install just

      - name: Run just lint
        run: just lint